---
- name: Include Vars
  include_vars:
    file: packages.yml
    name: packages

- name: Install KDE
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages.kde }}"