---
- hosts: all
  become: true
  become_user: root
  roles:
    - configs
    - pacman
    - aur

- hosts: all
  become: true
  become_user: root
  vars_prompt:
    - name: "nvidia"
      prompt: "Install Nvidia drivers?"
      private: no
      default: "no"
  tasks:
    - name: Install Nvidia drivers
      include_role:
        name: nvidia
      when: nvidia == "yes"

- hosts: all
  become: true
  become_user: root
  vars_prompt:
    - name: "kde"
      prompt: "Install KDE?"
      private: no
      default: "no"
  tasks:
    - name: Install KDE
      include_role:
        name: kde
      when: kde == "yes"
