---
# add variables here
- name: include variables
  include_vars: 
    file: packages.yml
    name: packages

- name: Create the `aur_builder` user
  become: true
  user:
    name: aur_builder
    create_home: true
    group: wheel
  changed_when: false

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"

- name: Install AUR packages
  kewlfft.aur.aur:
    use: auto
    name: "{{ item }}"
    state: present
    update_cache: false
  loop: "{{ packages.aur_added }}"

  become: true
  become_user: aur_builder

- name: Kill all tasks for the `aur_builder` user
  become: true
  become_user: root
  shell: pkill -u aur_builder 2>/dev/null || true
  ignore_errors: true
  changed_when: false

- name: Remove the `aur_builder` user
  become: true
  become_user: root
  user:
    name: aur_builder
    state: absent
  changed_when: false
