---
- name: Include secrets.yml
  include_vars:
    file: secrets.yml
    name: secrets

- name: Check if SDDM is installed
  shell: "pacman -Qs sddm"
  register: sddm_installed
  ignore_errors: true
  changed_when: false

- name: Check if Nvidia drivers are installed
  shell: "pacman -Qs nvidia"
  register: nvidia_installed
  ignore_errors: true
  changed_when: false

- name: Copy sddm.conf
  copy:
    src: ./files/sddm.conf
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: "0644"
  when: sddm_installed.rc == 0

- name: Copy nvidia.hook
  copy:
    src: ./files/nvidia.hook
    dest: /etc/pacman.d/hooks/nvidia.hook
    owner: root
    group: root
    mode: "0644"
  when: nvidia_installed.rc == 0

- name: pwd command
  shell: pwd
  register: pwd
  changed_when: false

- name: Symlink imperative_deletion.sh to /usr/local/bin/imperative_deletion
  file:
    src: "{{ pwd.stdout }}/imperative_deletion.sh"
    dest: /usr/local/bin/imperative_deletion
    state: link
    owner: root
    group: root
    mode: "0755"

- name: Copy Imperative Deletion Service
  copy:
    src: ./files/imperative-deletion.service
    dest: /etc/systemd/system/imperative-deletion.service
    owner: root
    group: root
    mode: "0755"

- name: Copy autorestic systemd services
  copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/.config/systemd/user/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  with_fileglob:
    - ./files/autorestic/*

- name: Enable autorestic systemd services
  systemd:
    name: "{{ item }}"
    scope: user
    daemon_reload: true
    enabled: true
    state: stopped
  with_items:
    - autorestic-backup.service
    - autorestic-prune.service

- name: Copy modules.conf
  copy:
    src: ./files/modules.conf
    dest: /etc/modules-load.d/modules.conf
    owner: root
    group: root
    mode: "0755"

- name: Copy logind.conf
  copy:
    src: ./files/logind.conf
    dest: /etc/systemd/logind.conf
    owner: root
    group: root
    mode: "0755"

- name: Restart logind service
  become_user: root
  systemd:
    name: systemd-logind
    state: restarted
  changed_when: false

- name: Enable XINPUT2 (gestures) in Firefox
  lineinfile:
    path: /etc/profile.d/use-xinput2.sh
    line: 'export MOZ_USE_XINPUT2=1'
    insertafter: EOF
    create: true

- name: Copy sshd.service
  copy:
    src: ./files/sshd.service
    dest: /usr/lib/systemd/system/sshd.service
    owner: root
    group: root
    mode: "0755"

- name: Enable sshd.service
  become_user: root
  systemd:
    name: sshd.service
    daemon_reload: true
    enabled: true
    state: started

- name: Enable imperative-deletion.service
  become_user: root
  systemd:
    name: imperative-deletion.service
    daemon_reload: true
    enabled: true
    state: stopped

- name: Enable IPv4 Forwarding
  become_user: root
  blockinfile:
    path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    block: |
      net.ipv4.conf.all.forwarding=1
    create: true

- name: Disable IPv6
  become_user: root
  blockinfile:
    path: /etc/sysctl.d/disabled_ipv6.conf
    block: |
      net.ipv6.conf.all.disable_ipv6=1
    create: true
