---
- name: include variables
  include_vars: 
    file: packages.yml
    name: packages

- name: Remove pacman packages
  become_user: root
  pacman:
    name: "{{ item }}"
    state: absent
    update_cache: false
  loop:
  - gnu-netcat # libvirt
  - iptables # we're installing iptables-nft, which is newer

- name: Install pacman packages
  become_user: root
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: false
  loop: "{{ packages.pacman_added }}"